In [2]:
# import library 
import tensorflow as tf 
import numpy      as np 
import matplotlib.pyplot as plt

np.random.seed(789); tf.set_random_seed(789)

In [6]:
# hyper parameter
num_epoch = 100 ; learning_rate = 0.0001; n_hidden = 100

Wx = tf.Variable(tf.random_normal(stddev=0.1,shape=[1,n_hidden]))
Wy = tf.Variable(tf.random_normal(stddev=0.1,shape=[1,n_hidden]))
b  = tf.Variable(tf.constant(0.1,shape=[n_hidden]))

Wout=tf.Variable(tf.random_normal(stddev=0.1,shape=[n_hidden,1]))
bout=tf.Variable(tf.constant(0.1,shape=[1]))

In [7]:
# build the graph
x  = tf.placeholder(tf.float32, [None,1])
y  = tf.placeholder(tf.float32, [None,1])
y_ = tf.placeholder(tf.float32, [None,1])

hidden_joint = tf.nn.relu(tf.matmul(x,Wx)+tf.matmul(y,Wy) +b)
out_joint    = tf.matmul(hidden_joint,Wout)+bout

hidden_marg  = tf.nn.relu(tf.matmul(x,Wx)+tf.matmul(y_,Wy)+b)
out_marg     = tf.matmul(hidden_marg, Wout)+bout
 
lower_bound  = tf.reduce_mean(out_joint) - tf.log(tf.reduce_mean(tf.exp(out_marg)))

In [9]:
# start the training
sig2= 0.2; N   = 5
for i in range(1):
    x_sample  = np.sign(np.random.normal(0.,1.,[N,1]))#np.random.normal(0.,1.,[N,1])
    y_sample  = x_sample+np.random.normal(0.,np.sqrt(sig2),[N,1])
    y_shuffle = np.random.permutation(y_sample)
    print(x_sample)
    print(y_sample)    
    print(y_shuffle)    

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[0.73599246]
 [1.13253739]
 [1.19366782]
 [1.35059116]
 [1.10137396]]
[[1.10137396]
 [0.73599246]
 [1.13253739]
 [1.35059116]
 [1.19366782]]


# Reference
1. MasanoriYamada/Mine_pytorch. (2018). GitHub. Retrieved 26 November 2018, from https://github.com/MasanoriYamada/Mine_pytorch/blob/master/mine.ipynb
2. What is information theory? What does entropy measure? Mutual information?. (2016). Charlesfrye.github.io. Retrieved 26 November 2018, from https://charlesfrye.github.io/stats/2016/03/29/info-theory-surprise-entropy.html
3. Mutual information estimation from samples via optimization. (2018). Mlmeetsdigcomm.wordpress.com. Retrieved 26 November 2018, from https://mlmeetsdigcomm.wordpress.com/2018/01/24/mutual-information-estimation-from-samples-via-optimization/comment-page-1/#comment-11
4. How to calculate mutual information with a NN + an application to GAN mode-dropping. (2018). Deep Learning Course Forums. Retrieved 26 November 2018, from https://forums.fast.ai/t/how-to-calculate-mutual-information-with-a-nn-an-application-to-gan-mode-dropping/14141
5. 